# Site Settings
title: Joseph's Data Science Portfolio
description: A Data Science student @ UNCC
url: https://SovereignJoseph.github.io/Data-Science-Portfolio
baseurl: /Data-Science-Portfolio

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.28.1"
minimal_mistakes_skin: "default"

# Plugins
plugins:
  - jekyll-include-cache

# Navigation
navbar:
  - title: "Home"
    url: /
  - title: "Projects"
    url: /projects/

# Author Profile (sidebar)
author:
  name: Joseph
  bio: "Data Science student @ UNCC"
  location: "Charlotte, NC"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SovereignJoseph"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/josephnounagnon"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SovereignJoseph"
